# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-05 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remote_peering', '0002_auto_20170405_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='ip',
            name='locations',
            field=models.ManyToManyField(to='remote_peering.Location'),
        ),
    ]
