# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-06 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remote_peering', '0003_ip_locations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ip',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='ipmetric',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
