# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-06 15:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('remote_peering', '0005_auto_20170406_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipmetric',
            name='ixp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='remote_peering.Ixp'),
        ),
    ]
